export const investorOrigin: string[] = [
  'Semua',
  'Asing',
  'Lokal'
]

export const investorType: string[] = [
  'Semua',
  'Other',
  'Bank',
  'Brokerage Firms',
  'Capital Market Supporting Institutions And Professions',
  'Commanditaire Vennootschap (CV) Or Limited Partnership',
  'Cooperatives',
  'Corporate',
  'Diocese',
  'Educational Institution',
  'Exchange Traded Funds',
  'Financial Institutional',
  'Firm',
  'Foundation',
  'Government',
  'Hedge Fund',
  'Individual',
  'Insurance',
  'International Organization',
  'Investment Advisors',
  'Investment Fund Selling Agent',
  'Investment Manager',
  'Mutual Funds',
  'Partnership',
  'Peer To Peer Lending',
  'Pension Funds',
  'PermanentEstablishment',
  'Private Bank',
  'Private Equity',
  'Securities Company',
  'Sole Proprietorship',
  'Sovereign Wealth Fund',
  'State Owned Company',
  'State Owned Enterprises',
  'Trustee Bank',
  'Venture Capital'
]